import type { YakuName } from './yaku';

export interface YakuReferenceEntry {
  id: YakuName;
  name: string;
  japaneseName: string;
  hanClosed: number | 'yakuman';
  hanOpen: number | 'yakuman' | null;
  description: string;
  requirements: string[];
  example: string;
  strategyTips: string[];
}

export const YAKU_REFERENCE_ENTRIES: YakuReferenceEntry[] = [
  {
    id: 'riichi',
    name: 'Riichi',
    japaneseName: 'Riichi',
    hanClosed: 1,
    hanOpen: null,
    description: 'Closed ready hand declared for one han and access to ura dora.',
    requirements: ['Closed hand', 'Hand is in tenpai', 'Declare riichi before winning'],
    example: '123m 456m 23p 678s 55p, declare riichi and win on 1p or 4p',
    strategyTips: ['Strong default line for closed hands.', 'Pairs well with pinfu, tanyao, and ura dora.'],
  },
  {
    id: 'double-riichi',
    name: 'Double Riichi',
    japaneseName: 'Daburu Riichi',
    hanClosed: 2,
    hanOpen: null,
    description: 'Riichi declared on your first uninterrupted turn.',
    requirements: ['Closed hand', 'First uninterrupted turn', 'Hand is in tenpai when declaring'],
    example: 'Starting hand reaches tenpai, declare double riichi, then win later',
    strategyTips: ['Do not break opening-tenpai hands lightly.', 'Value jumps quickly with ippatsu or ura dora.'],
  },
  {
    id: 'ippatsu',
    name: 'Ippatsu',
    japaneseName: 'Ippatsu',
    hanClosed: 1,
    hanOpen: null,
    description: 'Win within one uninterrupted turn after declaring riichi.',
    requirements: ['Riichi declared', 'No calls interrupt the turn', 'Win before your next discard'],
    example: 'Riichi, then ron the very next discard before any call',
    strategyTips: ['Fast closed riichi hands gain a lot from this bonus.', 'Opponents may call to cancel it.'],
  },
  {
    id: 'menzen-tsumo',
    name: 'Menzen Tsumo',
    japaneseName: 'Menzen Tsumo',
    hanClosed: 1,
    hanOpen: null,
    description: 'Closed self-draw win.',
    requirements: ['Closed hand', 'Win by tsumo'],
    example: '123m 456m 345p 678s 22p, tsumo 2p',
    strategyTips: ['Encourages keeping efficient closed shapes.', 'Common with riichi and pinfu hands.'],
  },
  {
    id: 'tanyao',
    name: 'Tanyao',
    japaneseName: 'Tanyao',
    hanClosed: 1,
    hanOpen: 1,
    description: 'All tiles are simples with no terminals or honors.',
    requirements: ['No 1, 9, or honor tiles', 'All sets and pair use 2-8 tiles'],
    example: '234m 456m 345p 678s 66p',
    strategyTips: ['Very flexible and efficient.', 'Often combines with pinfu, riichi, and dora.'],
  },
  {
    id: 'pinfu',
    name: 'Pinfu',
    japaneseName: 'Pinfu',
    hanClosed: 1,
    hanOpen: null,
    description: 'A hand made entirely of sequences with a valueless pair and a two-sided wait.',
    requirements: ['Closed hand', 'Four sequences', 'No value pair', 'Two-sided wait'],
    example: '123m 456m 234p 678s 55p, winning on 3p or 6p',
    strategyTips: ['Often combined with riichi and tanyao.', 'Prioritize keeping sequence shapes.'],
  },
  {
    id: 'iipeikou',
    name: 'Iipeikou',
    japaneseName: 'Iipeikou',
    hanClosed: 1,
    hanOpen: null,
    description: 'Two identical sequences in the same suit.',
    requirements: ['Closed hand', 'One pair of identical sequences in one suit'],
    example: '223344m 456p 678s 55p',
    strategyTips: ['Natural in closed sequence-heavy hands.', 'Be careful not to open the hand and lose it.'],
  },
  {
    id: 'yakuhai',
    name: 'Yakuhai',
    japaneseName: 'Yakuhai',
    hanClosed: 1,
    hanOpen: 1,
    description: 'Triplet or quad of dragons, seat wind, or round wind.',
    requirements: ['Triplet or quad of dragons, seat wind, or round wind'],
    example: 'RRR 234m 345p 678s 55s',
    strategyTips: ['Reliable open yaku when speed matters.', 'Seat/round winds can make awkward honors valuable.'],
  },
  {
    id: 'haitei',
    name: 'Haitei',
    japaneseName: 'Haitei Raoyue',
    hanClosed: 1,
    hanOpen: 1,
    description: 'Win by self-drawing the last live wall tile.',
    requirements: ['Win by tsumo', 'The winning tile is the final draw from the live wall'],
    example: 'Tenpai on the final live draw, tsumo the winning tile',
    strategyTips: ['Rare but free value.', 'Late-round tenpai pressure can matter.'],
  },
  {
    id: 'houtei',
    name: 'Houtei',
    japaneseName: 'Houtei Raoyui',
    hanClosed: 1,
    hanOpen: 1,
    description: 'Win on the final discard of the hand.',
    requirements: ['Win by ron', 'The winning tile is the final discard'],
    example: 'Ron the last discard on your wait',
    strategyTips: ['Rare but relevant in exhaustive endgames.', 'Pushes some late-call spots.'],
  },
  {
    id: 'rinshan-kaihou',
    name: 'Rinshan Kaihou',
    japaneseName: 'Rinshan Kaihou',
    hanClosed: 1,
    hanOpen: 1,
    description: 'Win on the supplemental tile drawn after a kan.',
    requirements: ['Declare kan', 'Win on the rinshan draw'],
    example: 'Kan 7777m, draw replacement tile, tsumo to complete hand',
    strategyTips: ['Only matters in kan-heavy lines.', 'Consider extra risk from opening kan.'],
  },
  {
    id: 'chankan',
    name: 'Chankan',
    japaneseName: 'Chankan',
    hanClosed: 1,
    hanOpen: 1,
    description: 'Robbing another player’s added kan for the win.',
    requirements: ['Opponent upgrades a pon to a kan', 'Your winning tile is the added tile'],
    example: 'Opponent adds the fourth 5p to a pon, you ron it',
    strategyTips: ['Very situational.', 'Stay aware of live waits against visible pon sets.'],
  },
  {
    id: 'chiitoitsu',
    name: 'Chitoitsu',
    japaneseName: 'Chiitoitsu',
    hanClosed: 2,
    hanOpen: null,
    description: 'Seven distinct pairs.',
    requirements: ['Closed hand', 'Seven different pairs', 'No duplicated pair types beyond two tiles'],
    example: '11m 22m 33p 44p 55s EE RR',
    strategyTips: ['Do not force standard shapes when pairs keep accumulating.', 'Tile acceptance is narrower than standard hands.'],
  },
  {
    id: 'ittsu',
    name: 'Ittsu',
    japaneseName: 'Ikkitsuukan',
    hanClosed: 2,
    hanOpen: 1,
    description: '123, 456, and 789 in the same suit.',
    requirements: ['Sequences 123, 456, and 789 in one suit'],
    example: '123m 456m 789m 345p 55s',
    strategyTips: ['Strong when a suit naturally fills in.', 'Open value drops, so judge speed versus points.'],
  },
  {
    id: 'sanshoku-doujun',
    name: 'Sanshoku Doujun',
    japaneseName: 'Sanshoku Doujun',
    hanClosed: 2,
    hanOpen: 1,
    description: 'The same sequence appears in all three suits.',
    requirements: ['Matching sequence in man, pin, and sou'],
    example: '456m 456p 456s 234m 55p',
    strategyTips: ['Worth preserving when you already hold cross-suit alignment.', 'Open calls reduce value by one han.'],
  },
  {
    id: 'chanta',
    name: 'Chanta',
    japaneseName: 'Chanta',
    hanClosed: 2,
    hanOpen: 1,
    description: 'Every set and the pair contains a terminal or honor, with at least one sequence.',
    requirements: ['Every group uses a terminal or honor', 'At least one sequence'],
    example: '123m 789m 111p 999s EE',
    strategyTips: ['Can become expensive with honors, but shape quality is often poor.', 'Avoid overcommitting if the hand is slow.'],
  },
  {
    id: 'sanshoku-doukou',
    name: 'Sanshoku Doukou',
    japaneseName: 'Sanshoku Doukou',
    hanClosed: 2,
    hanOpen: 2,
    description: 'The same numbered triplet in all three suits.',
    requirements: ['Matching triplets in man, pin, and sou'],
    example: '777m 777p 777s 123m EE',
    strategyTips: ['Often appears in triplet-oriented hands.', 'Natural partner with toitoi.'],
  },
  {
    id: 'sanankou',
    name: 'Sanankou',
    japaneseName: 'Sanankou',
    hanClosed: 2,
    hanOpen: 2,
    description: 'Three concealed triplets.',
    requirements: ['Three triplets or quads completed without calling them'],
    example: '111m 444p 777s 345m EE',
    strategyTips: ['Concealed triplets can justify slower lines.', 'Be careful about ron waits that change block interpretation.'],
  },
  {
    id: 'sankantsu',
    name: 'Sankantsu',
    japaneseName: 'Sankantsu',
    hanClosed: 2,
    hanOpen: 2,
    description: 'Three quads in one hand.',
    requirements: ['Three kan sets'],
    example: '1111m 5555p 9999s 123m EE',
    strategyTips: ['Rare and volatile.', 'Extra dora and rinshan access can swing value.'],
  },
  {
    id: 'toitoi',
    name: 'Toitoi',
    japaneseName: 'Toitoihou',
    hanClosed: 2,
    hanOpen: 2,
    description: 'All sets are triplets or quads.',
    requirements: ['Four triplet or quad sets', 'One pair'],
    example: '111m 444p 777s RRR EE',
    strategyTips: ['Reliable open scoring hand.', 'Value honors and dora pairs become stronger.'],
  },
  {
    id: 'honroutou',
    name: 'Honroutou',
    japaneseName: 'Honroutou',
    hanClosed: 2,
    hanOpen: 2,
    description: 'Only terminals and honors.',
    requirements: ['Every tile is a terminal or honor'],
    example: '111m 999m 111p RRR EE',
    strategyTips: ['Usually overlaps with toitoi or chiitoitsu.', 'Shape is rigid but scoring is stable.'],
  },
  {
    id: 'shousangen',
    name: 'Shousangen',
    japaneseName: 'Shousangen',
    hanClosed: 2,
    hanOpen: 2,
    description: 'Two dragon triplets/quads plus a pair of the third dragon.',
    requirements: ['Two dragon triplets or quads', 'Pair of the remaining dragon'],
    example: 'RRR GGG WhWh 123m 456p',
    strategyTips: ['Keep dragon pairs alive when two dragon sets appear.', 'Commonly stacks with yakuhai.'],
  },
  {
    id: 'ryanpeikou',
    name: 'Ryanpeikou',
    japaneseName: 'Ryanpeikou',
    hanClosed: 3,
    hanOpen: null,
    description: 'Two separate iipeikou patterns in a closed hand.',
    requirements: ['Closed hand', 'Two different pairs of identical sequences'],
    example: '223344m 556677p 88s',
    strategyTips: ['Very strong but fragile closed hand pattern.', 'Do not open and break duplicate sequences.'],
  },
  {
    id: 'honitsu',
    name: 'Honitsu',
    japaneseName: 'Honitsu',
    hanClosed: 3,
    hanOpen: 2,
    description: 'One suit plus honors.',
    requirements: ['All suited tiles are in one suit', 'Honors allowed'],
    example: '123m 456m 789m EEE 55m',
    strategyTips: ['Great fallback when one suit dominates and honors support it.', 'Open value is still respectable.'],
  },
  {
    id: 'junchan',
    name: 'Junchan',
    japaneseName: 'Junchan Taiyaochuu',
    hanClosed: 3,
    hanOpen: 2,
    description: 'Every set and pair contains a terminal, with no honors.',
    requirements: ['Every group contains a 1 or 9', 'At least one sequence', 'No honors'],
    example: '123m 789m 123p 789s 11s',
    strategyTips: ['Harder than chanta because honors are excluded.', 'Be honest about speed loss if the shape is clumsy.'],
  },
  {
    id: 'chinitsu',
    name: 'Chinitsu',
    japaneseName: 'Chinitsu',
    hanClosed: 6,
    hanOpen: 5,
    description: 'All tiles are in one suit with no honors.',
    requirements: ['Every tile is in exactly one suit', 'No honors'],
    example: '123m 456m 789m 345m 55m',
    strategyTips: ['One of the best value routes when a flush is natural.', 'Discarding off-suit tiles early improves concealment.'],
  },
  {
    id: 'kokushi-musou',
    name: 'Kokushi Musou',
    japaneseName: 'Kokushi Musou',
    hanClosed: 'yakuman',
    hanOpen: null,
    description: 'Thirteen orphans with one duplicate among the thirteen terminals and honors.',
    requirements: ['Closed hand', 'All 13 terminal and honor types', 'One duplicate among them'],
    example: '1m 9m 1p 9p 1s 9s E S W N R G Wh + duplicate 1m',
    strategyTips: ['Commit only when terminals and honors cluster heavily.', 'Middle tiles are nearly always dead weight here.'],
  },
  {
    id: 'chuuren-poutou',
    name: 'Chuuren Poutou',
    japaneseName: 'Chuuren Poutou',
    hanClosed: 'yakuman',
    hanOpen: null,
    description: 'Nine gates in one suit.',
    requirements: ['Closed hand', '1112345678999 in one suit', 'Any extra tile in that suit'],
    example: '1112345678999m + any man tile',
    strategyTips: ['Extremely rare flush yakuman.', 'Only realistic when one suit overwhelms the draw.'],
  },
  {
    id: 'suuankou',
    name: 'Suuankou',
    japaneseName: 'Suuankou',
    hanClosed: 'yakuman',
    hanOpen: null,
    description: 'Four concealed triplets.',
    requirements: ['Four concealed triplets or quads', 'Closed hand'],
    example: '111m 444p 777s RRR EE, tsumo E',
    strategyTips: ['Concealed triplets justify patience.', 'Do not open away your yakuman route.'],
  },
  {
    id: 'suukantsu',
    name: 'Suukantsu',
    japaneseName: 'Suukantsu',
    hanClosed: 'yakuman',
    hanOpen: 'yakuman',
    description: 'Four quads in one hand.',
    requirements: ['Four kan sets'],
    example: '1111m 2222p 3333s RRRR EE',
    strategyTips: ['Very rare and high variance.', 'Track extra dora and risk from opening kans.'],
  },
  {
    id: 'ryuuiisou',
    name: 'Ryuuiisou',
    japaneseName: 'Ryuuiisou',
    hanClosed: 'yakuman',
    hanOpen: 'yakuman',
    description: 'All green tiles.',
    requirements: ['Only 2s, 3s, 4s, 6s, 8s, and green dragons'],
    example: '222s 333s 444s 666s GG',
    strategyTips: ['Watch for souzu-heavy dragon hands.', 'Do not accidentally add non-green tiles.'],
  },
  {
    id: 'chinroutou',
    name: 'Chinroutou',
    japaneseName: 'Chinroutou',
    hanClosed: 'yakuman',
    hanOpen: 'yakuman',
    description: 'All terminals.',
    requirements: ['Every tile is 1 or 9', 'No honors'],
    example: '111m 999m 111p 999s 11s',
    strategyTips: ['Usually forces triplet structure.', 'Expect poor tile acceptance.'],
  },
  {
    id: 'tsuuiisou',
    name: 'Tsuuiisou',
    japaneseName: 'Tsuuiisou',
    hanClosed: 'yakuman',
    hanOpen: 'yakuman',
    description: 'All honors.',
    requirements: ['Every tile is a wind or dragon'],
    example: 'EEE SSS WWW RRR GG',
    strategyTips: ['Honor-heavy starts can pivot here.', 'Visibility is high, so speed matters.'],
  },
  {
    id: 'daisangen',
    name: 'Daisangen',
    japaneseName: 'Daisangen',
    hanClosed: 'yakuman',
    hanOpen: 'yakuman',
    description: 'Three dragon triplets or quads.',
    requirements: ['Red, green, and white dragon triplets/quads'],
    example: 'RRR GGG WhWhWh 123m 55p',
    strategyTips: ['One of the most practical yakuman routes.', 'Dragon calls are often correct when speed is good.'],
  },
  {
    id: 'shousuushii',
    name: 'Shousuushii',
    japaneseName: 'Shousuushii',
    hanClosed: 'yakuman',
    hanOpen: 'yakuman',
    description: 'Three wind triplets/quads and a pair of the fourth wind.',
    requirements: ['Three wind triplets/quads', 'Pair of the remaining wind'],
    example: 'EEE SSS WWW NN 123m',
    strategyTips: ['Wind clusters justify heavy commitment.', 'Seat and round wind value can bridge into it.'],
  },
  {
    id: 'daisuushii',
    name: 'Daisuushii',
    japaneseName: 'Daisuushii',
    hanClosed: 'yakuman',
    hanOpen: 'yakuman',
    description: 'Four wind triplets or quads.',
    requirements: ['East, south, west, and north triplets/quads'],
    example: 'EEE SSS WWW NNN 55m',
    strategyTips: ['Very visible but devastating.', 'Wind pon chains are a strong signal to commit.'],
  },
  {
    id: 'dora',
    name: 'Dora',
    japaneseName: 'Dora',
    hanClosed: 0,
    hanOpen: 0,
    description: 'Bonus han from matching dora indicators.',
    requirements: ['Hold tiles matching the current dora indicators'],
    example: 'Indicator 4m makes 5m a dora tile',
    strategyTips: ['Dora add value but do not form a legal yaku by themselves.', 'Avoid overvaluing isolated dora without a scoring plan.'],
  },
  {
    id: 'red-dora',
    name: 'Red Dora',
    japaneseName: 'Aka Dora',
    hanClosed: 0,
    hanOpen: 0,
    description: 'Bonus han from red fives.',
    requirements: ['Hand contains a red five tile'],
    example: '0m counts as one red dora',
    strategyTips: ['Treat red fives as flexible value tiles.', 'They still do not replace a real yaku.'],
  },
  {
    id: 'ura-dora',
    name: 'Ura Dora',
    japaneseName: 'Ura Dora',
    hanClosed: 0,
    hanOpen: null,
    description: 'Bonus han revealed after winning with riichi.',
    requirements: ['Win after riichi', 'Matching ura dora indicators'],
    example: 'Riichi win reveals ura indicator giving extra 3p dora',
    strategyTips: ['Only available after riichi.', 'Makes good riichi decisions more rewarding.'],
  },
  {
    id: 'kan-dora',
    name: 'Kan Dora',
    japaneseName: 'Kan Dora',
    hanClosed: 0,
    hanOpen: 0,
    description: 'Additional dora indicators revealed after kans.',
    requirements: ['A kan was declared', 'Matching kan dora indicators'],
    example: 'After a kan, extra indicator makes 7s dora',
    strategyTips: ['Kans can spike hand value but also give opponents information.', 'Do not kan automatically.'],
  },
  {
    id: 'kan-ura-dora',
    name: 'Kan Ura Dora',
    japaneseName: 'Kan Ura Dora',
    hanClosed: 0,
    hanOpen: null,
    description: 'Additional ura dora revealed from kan indicators after riichi.',
    requirements: ['Riichi win', 'A kan occurred', 'Matching kan ura indicators'],
    example: 'Riichi hand wins after a kan and gains extra ura dora from kan indicators',
    strategyTips: ['High variance bonus on riichi-kan hands.', 'Never count on it as your only value source.'],
  },
];

export const YAKU_REFERENCE_BY_ID: Record<YakuName, YakuReferenceEntry> = Object.fromEntries(
  YAKU_REFERENCE_ENTRIES.map(entry => [entry.id, entry])
) as Record<YakuName, YakuReferenceEntry>;

export function getYakuReference(id: YakuName): YakuReferenceEntry {
  return YAKU_REFERENCE_BY_ID[id];
}
